### ISSUE TITLE
[XCM] Subquery Indexer stopped

### ISSUE THREAD

**Issue by trmaphi** [web3go-xyz/indexer-polkadot-xcm#3]
```
subquery-polkadot_1  | 2022-10-28T01:19:52.392Z <db> DEBUG Executing (53ba3aa4-c0e2-45b8-b39a-c788cab06a14): ROLLBACK; 
subquery-polkadot_1  | 2022-10-28T01:19:52.677Z <fetch> ERROR failed to index block at height 12533787  
subquery-polkadot_1  | TypeError: this[#raw].toBn is not a function
subquery-polkadot_1  |     at Type.toU8a (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types-codec/cjs/base/Compact.js:196:46)
subquery-polkadot_1  |     at Map.toU8a (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types-codec/cjs/native/Struct.js:303:24)
subquery-polkadot_1  |     at Map.toU8a (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types-codec/cjs/native/Struct.js:303:24)
subquery-polkadot_1  |     at Map.toU8a (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types-codec/cjs/native/Struct.js:303:24)
subquery-polkadot_1  |     at Type.toU8aInner (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:368:56)
subquery-polkadot_1  |     at Type.toU8a (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:361:50)
subquery-polkadot_1  |     at Type.toHex (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:319:37)
subquery-polkadot_1  |     at Type.toJSON (/usr/local/lib/node_modules/@subql/node/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:344:17)
subquery-polkadot_1  |     at JSON.stringify (<anonymous>)
subquery-polkadot_1  |     at IndexerSandbox.securedExec (/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js:82:38)
```

**Comment by happyJ2024** [comment]
- [x] check polkadot.js version 
- [x] check docker image version provided by subquery team.

**Comment by trmaphi** [comment]
node_modules problem, for the old build of docker image
